[package]
name = "pretty-print"
version = "0.1.0"
edition = "2021"
authors = ["Irfan Eralp Kavakli"]
description = "A macro to simplify pretty-printing complex structures in Rust"
license = "MIT"
repository = "https://github.com/bulpara/pretty-print"

[dependencies]
